CREATE TABLE NOTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    cue TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TRIGGER update_notes_timestamp 
AFTER UPDATE ON NOTES
BEGIN
    UPDATE NOTES SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;